### ISSUE TITLE
Restart countdown when it ends

### ISSUE THREAD

**Issue by narimonfund** [impress-org/Give-Form-Countdown#24]
## Issue Overview

Hi,
I just created my account and I don't know code! 

Enhancement/suggestion:

I would like the countdown resets and restarts when it reaches its end. So I don't have to set it up every (for example 30 days.

## Current Behavior

Currently under the "End Message Position" there is only 3 options (which are technically two options,either keep it open or close the form then show a message.

The difference would be: 
I would like another option: 
Keep it open and restart the timer for another 30 days (for example if I set it to 30 days).

## Expected Behavior

Countdown restarts when it reaches its end.
## Possible Solution

Addition of another option.  I know no codes. Can't help with that.

## Steps to Reproduce (for bugs)

This is not a bug, but an enhancement or suggestion.

**Comment by mathetos** [comment]
Closing for now. I don't believe this will benefit the majority of users and is a niche case.
