### ISSUE TITLE
fix: add plugin documentation link in plugin page

### ISSUE THREAD

**Issue by raftaar1191** [impress-org/Give-Form-Countdown#33]
## Issue Overview
We should provide admin with plugin documentation page link in the plugin activation page

## Expected Behavior
![image](https://user-images.githubusercontent.com/22215595/45806218-1e2fa280-bcde-11e8-824d-83a281101641.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/22215595/45805981-8631b900-bcdd-11e8-9c18-3e1c8c2cba05.png)

**Comment by mathetos** [comment]
Closing as we don't have online docs and I don't believe they are needed for such a simple and free add-on.
