### ISSUE TITLE
fix: support the j F Y date format

### ISSUE THREAD

**Issue by Benunc** [impress-org/Give-Form-Countdown#34]
## Issue Overview
The form countdown does not work at all for `j F Y` date formats.

## Current Behavior
With a site in `j F Y`date format, the form will always show as being done, no matter what date you put in.

## Expected Behavior
I expect all date formats to be supported.

## Steps to Reproduce (for bugs)
1. Change date format in General Settings to `j F Y`
2. Install and activate form countdown
3. set the date that a countdown ends to the future using the datepicker
4. I will show as finished already on the front end. 

## Related
https://secure.helpscout.net/conversation/823178039/37303/

## Acceptance Criteria
- [ ] `j F Y` date formats work
- [ ] other date formats also are unaffected.

**Comment by mathetos** [comment]
@Benunc I just tested and can not replicate with Give Core version `2.4.5` I know we had some other date-related issues with Give Core so perhaps those fixed this.

Can you test again please to confirm?

**Comment by mikejhale** [comment]
@Benunc Can you verify if this is still an issue?

**Comment by DevinWalker** [comment]
This plugin has been removed for lack of support and adoption - closing.
