### ISSUE TITLE
fix: GIthub security alerts

### ISSUE THREAD

**Issue by mathetos** [impress-org/Give-Form-Countdown#35]
## Issue Overview
Github is throwing alerts about our build files:
![image](https://user-images.githubusercontent.com/930724/56321513-b3333680-611b-11e9-9fb2-f87c2c38844f.png)

https://github.com/impress-org/give-form-countdown/network/alerts

## Possible Solution
Update build scripts

## Related PRs
-- PR forthcoming

**Comment by mathetos** [comment]
@ravinderk It seems the only reason we have NPM and Gulp at all is to generate the Readme.md file based on the readme.txt file. 

If it's ok with you I say we remove all of that. It's more hassle than benefit for such a small plugin that doesn't get updated often.

**Comment by DevinWalker** [comment]
Those files aren't actually shipped in the production zip so it's a non-vulnerability. 

![2019-04-17_17-29-33](https://user-images.githubusercontent.com/1571635/56329061-9d7f3a80-6136-11e9-92b0-3a5ff9375756.png)

The alert shouldn't display anymore.
