### ISSUE TITLE
fix: prevent donation goal alert appearing by default

### ISSUE THREAD

**Issue by mathetos** [impress-org/Give-Form-Countdown#36]
## Issue Overview
The "Donation Goal" alert currently displays even when the Goal is disabled completely. 

![image](https://user-images.githubusercontent.com/930724/56324115-d4e3ec00-6122-11e9-8a9c-6ea0477f9d50.png)

![image](https://user-images.githubusercontent.com/930724/56324126-dd3c2700-6122-11e9-92bc-c707eae867f9.png)

## Possible Solution

Check the logic and make it smarter :-)

**Comment by mathetos** [comment]
Looks like this is happening because the "Use Donation End Message" is set to "Disabled" by default, and is hidden from view when the Goal is also disabled. So we need to check for whether the Goal is enabled as well before showing that message.

![image](https://user-images.githubusercontent.com/930724/56325618-af0d1600-6127-11e9-8812-f0d2eff40e25.png)

**Comment by DevinWalker** [comment]
This plugin has been removed for lack of support and adoption - closing.
